sdk/build.gradle, sdk/src/main/java/com/meniga/sdk/models/categories/MenigaCategory.java
Correcting the way user categories are included when fetching categories.
=> MOBILE-1753 and MOBILE-1754 use rcats

sdk/build.gradle, sdk/src/main/java/com/meniga/sdk/models/accounts/MenigaAccount.java
Fixing a problem that caused isDisabled not to be parsed in the sdk.
=> MOBILE-1764 Disabled accounts

sdk/build.gradle, sdk/src/main/java/com/meniga/sdk/webservices/MenigaAPI.java, sdk/src/main/java/com/meniga/sdk/webservices/PersistenceDelegate.java, sdk/src/main/java/com/meniga/sdk/webservices/requests/AcceptChallenge.java
Updating the sdk so that accepting challenges will work correctly.
=> MOBILE-1766 spending meter calculation issues when saving

sdk/build.gradle, sdk/src/main/java/com/meniga/sdk/models/offers/redemptions/enums/RedemptionType.java
Offer redemption types have changed, updating.
=> MOBILE-1803 "redemptionType":"PartUnderMinAccumulatedAmount"

sdk/build.gradle, sdk/src/main/java/com/meniga/sdk/models/categories/MenigaCategory.java, sdk/src/main/java/com/meniga/sdk/models/categories/operators/MenigaCategoryOperations.java, sdk/src/main/java/com/meniga/sdk/models/categories/operators/MenigaCategoryOperationsImp.java, sdk/src/main/java/com/meniga/sdk/webservices/MenigaAPI.java, sdk/src/main/java/com/meniga/sdk/webservices/PersistenceDelegate.java, sdk/src/main/java/com/meniga/sdk/webservices/requests/GetCategoryById.java
Now all category calls take the culture parameter to make sure the category language is correct.
=> MOBILE-1801 Category language not updating in tdv

sdk/build.gradle, sdk/src/main/java/com/meniga/sdk/models/user/MenigaUser.java, sdk/src/main/java/com/meniga/sdk/models/user/operators/MenigaUserOperations.java, sdk/src/main/java/com/meniga/sdk/models/user/operators/MenigaUserOperationsImp.java, sdk/src/main/java/com/meniga/sdk/webservices/APIConst.java, sdk/src/main/java/com/meniga/sdk/webservices/MenigaAPI.java, sdk/src/main/java/com/meniga/sdk/webservices/PersistenceDelegate.java, sdk/src/main/java/com/meniga/sdk/webservices/requests/ForgotPassword.java
Added functionality for resetting password.
=> MOBILE-1806 Issues with Forgot password

sdk/build.gradle, sdk/src/main/java/com/meniga/sdk/webservices/requests/GetRealmAuthMethod.java
Making the request for bank aggregation correct.
=> Making the request for bank aggregation correct.

sdk/build.gradle, sdk/src/main/java/com/meniga/sdk/models/terms/MenigaTermType.java, sdk/src/main/java/com/meniga/sdk/models/terms/MenigaTerms.java, sdk/src/main/java/com/meniga/sdk/models/terms/operators/MenigaTermsOperations.java, sdk/src/main/java/com/meniga/sdk/models/terms/operators/MenigaTermsOperationsImp.java, sdk/src/main/java/com/meniga/sdk/webservices/APIConst.java, sdk/src/main/java/com/meniga/sdk/webservices/MenigaAPI.java, sdk/src/main/java/com/meniga/sdk/webservices/PersistenceDelegate.java, sdk/src/main/java/com/meniga/sdk/webservices/requests/AcceptTerms.java, sdk/src/main/java/com/meniga/sdk/webservices/requests/DeclineTerms.java, sdk/src/main/java/com/meniga/sdk/webservices/requests/GetTermTypes.java
Added missing terms functionality.
=> MOBILE-1845 Call the terms accept api when creating new user

sdk/build.gradle, sdk/src/main/java/com/meniga/sdk/models/terms/MenigaTerms.java, sdk/src/main/java/com/meniga/sdk/models/terms/operators/MenigaTermsOperations.java, sdk/src/main/java/com/meniga/sdk/models/terms/operators/MenigaTermsOperationsImp.java, sdk/src/main/java/com/meniga/sdk/webservices/MenigaAPI.java, sdk/src/main/java/com/meniga/sdk/webservices/PersistenceDelegate.java, sdk/src/main/java/com/meniga/sdk/webservices/requests/GetTermTypes.java, sdk/src/main/java/com/meniga/sdk/webservices/requests/GetTerms.java
Now sending which language we want the terms to be delivered in.
=> MOBILE-1859 terms language

sdk/build.gradle, sdk/src/main/java/com/meniga/sdk/models/serverpublic/MenigaPublicSettings.java
Added an option for getting currency format using currency code instead of currency symbol ($ 15 vs USD 15).
=> improv/MOBILE-1877 Currency Code Option

sdk/build.gradle, sdk/src/main/java/com/meniga/sdk/models/challenges/MenigaChallenge.java, sdk/src/main/java/com/meniga/sdk/models/challenges/operators/MenigaChallengesOperationsImp.java, sdk/src/main/java/com/meniga/sdk/webservices/requests/UpdateChallenge.java
Added logic so that users of the sdk can edit a challenge.
=> MOBILE-1849 Edit and delete challenges

sdk/build.gradle, sdk/src/main/java/com/meniga/sdk/models/budget/MenigaBudgetEntry.java, sdk/src/main/java/com/meniga/sdk/models/budget/operators/MenigaBudgetOperations.java, sdk/src/main/java/com/meniga/sdk/models/budget/operators/MenigaBudgetOperationsImp.java, sdk/src/main/java/com/meniga/sdk/webservices/APIConst.java, sdk/src/main/java/com/meniga/sdk/webservices/MenigaAPI.java, sdk/src/main/java/com/meniga/sdk/webservices/PersistenceDelegate.java, sdk/src/main/java/com/meniga/sdk/webservices/requests/UpdateBudget.java
Users can now update their budgets.
=> feat/MOBILE-2003 Add planning budget edit

sdk/build.gradle, sdk/src/main/java/com/meniga/sdk/models/offers/MenigaOffersSettings.java
Re-enabling the soon-to-be-deprecated terms acceptance in the offers endpoint.
=> bug/MENIGA-2051 Use new terms endpoint

sdk/build.gradle, sdk/src/main/java/com/meniga/sdk/MenigaSDK.java, sdk/src/main/java/com/meniga/sdk/models/organizations/MenigaRealmAuthParameter.java, sdk/src/main/java/com/meniga/sdk/webservices/WebClient.java, sdk/src/main/java/com/meniga/sdk/webservices/interceptors/AcceptLanguageInterceptor.java
Added a new interceptor for adding a language header.
=> Added a new interceptor for adding a language header.

sdk/build.gradle, sdk/src/main/java/com/meniga/sdk/models/organizations/MenigaRealm.java, sdk/src/main/java/com/meniga/sdk/models/organizations/MenigaRealmAuthResponse.java, sdk/src/main/java/com/meniga/sdk/models/organizations/operators/MenigaRealmOperations.java, sdk/src/main/java/com/meniga/sdk/models/organizations/operators/MenigaRealmOperationsImp.java, sdk/src/main/java/com/meniga/sdk/webservices/MenigaAPI.java, sdk/src/main/java/com/meniga/sdk/webservices/PersistenceDelegate.java, sdk/src/main/java/com/meniga/sdk/webservices/requests/AddRealmAccountsToMeniga.java
Updating the account aggregation logic.
=> Updating the account aggregation logic.

sdk/build.gradle
Have to increment version to force code changes.
=> Have to increment version to force code changes.

sdk/build.gradle, sdk/src/main/java/com/meniga/sdk/models/organizations/MenigaRealm.java, sdk/src/main/java/com/meniga/sdk/models/organizations/operators/MenigaRealmOperations.java, sdk/src/main/java/com/meniga/sdk/models/organizations/operators/MenigaRealmOperationsImp.java, sdk/src/main/java/com/meniga/sdk/webservices/MenigaAPI.java, sdk/src/main/java/com/meniga/sdk/webservices/PersistenceDelegate.java, sdk/src/main/java/com/meniga/sdk/webservices/requests/GetRealmAuthMethod.java
Some more change to make bank aggregation work.
=> Some more change to make bank aggregation work.

sdk/build.gradle, sdk/src/main/java/com/meniga/sdk/models/transactions/MenigaTransaction.java
Implementing a way to submit many transaction filters at once.
=> Implementing a way to submit many transaction filters at once.

sdk/build.gradle, sdk/src/main/java/com/meniga/sdk/models/feed/MenigaAccountEvent.java, sdk/src/main/java/com/meniga/sdk/models/feed/MenigaCustomEvent.java, sdk/src/main/java/com/meniga/sdk/models/feed/MenigaEvent.java, sdk/src/main/java/com/meniga/sdk/models/feed/MenigaFeedItem.java, sdk/src/main/java/com/meniga/sdk/models/feed/MenigaOfferEvent.java, sdk/src/main/java/com/meniga/sdk/models/feed/MenigaScheduledEvent.java
Reverting back to using date instead of originalDate.
=> Reverting back to using date instead of originalDate.

sdk/build.gradle
Forcing all changes into a new version.
=> Forcing all changes into a new version.

sdk/build.gradle, sdk/src/main/java/com/meniga/sdk/models/organizations/MenigaRealm.java, sdk/src/main/java/com/meniga/sdk/models/organizations/operators/MenigaRealmOperations.java, sdk/src/main/java/com/meniga/sdk/models/organizations/operators/MenigaRealmOperationsImp.java, sdk/src/main/java/com/meniga/sdk/webservices/MenigaAPI.java, sdk/src/main/java/com/meniga/sdk/webservices/PersistenceDelegate.java, sdk/src/main/java/com/meniga/sdk/webservices/requests/GetRealmAccounts.java, sdk/src/main/java/com/meniga/sdk/webservices/requests/GetRealmAuthMethod.java
Amending the auth call to always include a session token and also include it in the correct place.
=> bug/MOBILE-2272 Session tokens in auth

sdk/build.gradle, sdk/src/main/java/com/meniga/sdk/models/challenges/MenigaChallenge.java
Implementing changes needed for analytics.
=> Implementing changes needed for analytics.

sdk/build.gradle, sdk/src/main/java/com/meniga/sdk/converters/MenigaChallengesConverter.java, sdk/src/main/java/com/meniga/sdk/converters/MenigaReimbursementAccountConverter.java, sdk/src/main/java/com/meniga/sdk/models/sync/AccountSyncStatus.java, sdk/src/main/java/com/meniga/sdk/models/sync/MenigaSync.java, sdk/src/main/java/com/meniga/sdk/models/sync/RealmSyncResponse.java, sdk/src/test/java/com/meniga/sdk/models/MockClient.java
Now delivering the latest sync which contains all the processed accounts.
=> Now delivering the latest sync which contains all the processed accounts.

sdk/build.gradle, sdk/src/main/java/com/meniga/sdk/models/challenges/MenigaChallenge.java, sdk/src/main/java/com/meniga/sdk/models/challenges/operators/MenigaChallengesOperations.java, sdk/src/main/java/com/meniga/sdk/models/challenges/operators/MenigaChallengesOperationsImp.java, sdk/src/main/java/com/meniga/sdk/webservices/APIRequest.java, sdk/src/main/java/com/meniga/sdk/webservices/requests/CreateChallenge.java, sdk/src/main/java/com/meniga/sdk/webservices/requests/CreateChallengeTypeData.java
Added (optionally) challenge recurringInterval to the create function for challenges.
=> SDPOSTE-17

sdk/build.gradle, sdk/src/main/java/com/meniga/sdk/adapters/TaskAdapter.java, sdk/src/main/java/com/meniga/sdk/providers/BasicTaskAdapter.java
Now a cancelled interceptor task will not be run.
=> MOBILE-2370

sdk/build.gradle, sdk/src/main/java/com/meniga/sdk/models/challenges/MenigaChallenge.java, sdk/src/main/java/com/meniga/sdk/models/challenges/operators/MenigaChallengesOperations.java, sdk/src/main/java/com/meniga/sdk/models/challenges/operators/MenigaChallengesOperationsImp.java, sdk/src/main/java/com/meniga/sdk/webservices/APIConst.java, sdk/src/main/java/com/meniga/sdk/webservices/MenigaAPI.java, sdk/src/main/java/com/meniga/sdk/webservices/PersistenceDelegate.java, sdk/src/main/java/com/meniga/sdk/webservices/requests/DeleteChallenge.java, sdk/src/main/java/com/meniga/sdk/webservices/requests/GetChallengeHistory.java
Adding challenge history support.
=> MOBILE-2611

sdk/build.gradle, sdk/src/main/java/com/meniga/sdk/models/transactions/TransactionsFilter.java
Fixing a critical bug that caused transaction filter not to work at all.
=> MOBILE-2636

sdk/build.gradle, sdk/src/main/java/com/meniga/sdk/models/organizations/MenigaRealmAuthParameter.java, sdk/src/main/java/com/meniga/sdk/models/organizations/MenigaRealmAuthResponse.java
Now supporting merging users if they already exists during signup.
=> MOBILE-2634

sdk/build.gradle, sdk/src/main/java/com/meniga/sdk/models/transactions/TransactionsFilter.java, sdk/src/main/java/com/meniga/sdk/webservices/requests/GetTransactions.java
Removing items from transactions filter that are not used and also preventing the query map logic to include empty arrays.
=> MOBILE-2640

sdk/build.gradle, sdk/src/main/java/com/meniga/sdk/converters/MenigaBaseConverter.java, sdk/src/main/java/com/meniga/sdk/converters/MenigaCategoryConverter.java
Generic requests now include all the data returned from calls.
=> SDPOSTE-20

sdk/build.gradle, sdk/src/main/java/com/meniga/sdk/converters/MenigaChallengesConverter.java, sdk/src/main/java/com/meniga/sdk/eventconverters/EventBaseConverter.java, sdk/src/main/java/com/meniga/sdk/eventconverters/generic/BaseEventConverter.java, sdk/src/main/java/com/meniga/sdk/eventconverters/generic/MenigaAccountAvailableAmountEventConverter.java, sdk/src/main/java/com/meniga/sdk/eventconverters/generic/MenigaChallengeEventConverter.java, sdk/src/main/java/com/meniga/sdk/eventconverters/generic/MenigaCustomEventConverter.java, sdk/src/main/java/com/meniga/sdk/eventconverters/generic/MenigaDialogEventConverter.java, sdk/src/main/java/com/meniga/sdk/eventconverters/generic/MenigaTransactionCountEventConverter.java, sdk/src/main/java/com/meniga/sdk/eventconverters/generic/MenigaTransactionEventConverter.java, sdk/src/main/java/com/meniga/sdk/helpers/ChallengeItemFactory.java, sdk/src/main/java/com/meniga/sdk/helpers/FeedItemFactory.java
Now handling all challenge related events in feed.
=> MOBILE-2572 Challenges user events in feed

sdk/build.gradle, sdk/src/main/java/com/meniga/sdk/models/merchants/MenigaMerchant.java
Changed the data type for merchant detected category.
=> SDPOSTE-33

sdk/build.gradle, sdk/src/main/java/com/meniga/sdk/models/budget/MenigaBudget.java, sdk/src/main/java/com/meniga/sdk/models/budget/operators/CreateBudget.java, sdk/src/main/java/com/meniga/sdk/models/budget/operators/MenigaBudgetOperations.java, sdk/src/main/java/com/meniga/sdk/models/budget/operators/MenigaBudgetOperationsImp.java, sdk/src/main/java/com/meniga/sdk/webservices/MenigaAPI.java, sdk/src/main/java/com/meniga/sdk/webservices/PersistenceDelegate.java
Updated the method for creating a budget to reflect api changes.
=> SDPOSTE-26

sdk/build.gradle, sdk/src/main/java/com/meniga/sdk/models/feed/MenigaChallengeEvent.java, sdk/src/main/java/com/meniga/sdk/models/feed/MenigaChallengeEventData.java
Adding missing data fields to the challenge event.
=> MOBILE-2572

sdk/build.gradle, sdk/src/main/java/com/meniga/sdk/providers/tasks/Task.java, sdk/src/main/java/com/meniga/sdk/providers/tasks/TaskCompletionSource.java
Adding the originating request string to the task.
=> MOBILE-2740

sdk/build.gradle, sdk/src/main/java/com/meniga/sdk/models/transactions/MenigaTransaction.java
Added merchant list to transaction.
=> feat/MOBILE-2748 Add merchants list to transaction object

sdk/build.gradle, sdk/src/main/java/com/meniga/sdk/converters/MenigaBaseConverter.java, sdk/src/main/java/com/meniga/sdk/converters/MenigaCategoryConverter.java, sdk/src/main/java/com/meniga/sdk/converters/MenigaConverter.java, sdk/src/main/java/com/meniga/sdk/converters/MenigaFeedConverter.java, sdk/src/main/java/com/meniga/sdk/converters/MenigaFeedItemConverter.java, sdk/src/main/java/com/meniga/sdk/converters/MenigaIdNameKeyValConverter.java, sdk/src/main/java/com/meniga/sdk/converters/MenigaOfferConverter.java, sdk/src/main/java/com/meniga/sdk/converters/MenigaRedemptionConverter.java, sdk/src/main/java/com/meniga/sdk/converters/MenigaReimbursementAccountConverter.java, sdk/src/main/java/com/meniga/sdk/converters/MenigaTransactionUpdateConverter.java, sdk/src/main/java/com/meniga/sdk/converters/MenigaTransactionsConverter.java, sdk/src/main/java/com/meniga/sdk/models/transactions/MenigaTransaction.java, sdk/src/main/java/com/meniga/sdk/models/transactions/MenigaTransactionUpdate.java, sdk/src/main/java/com/meniga/sdk/models/transactions/operators/MenigaTransactionOperations.java, sdk/src/main/java/com/meniga/sdk/models/transactions/operators/MenigaTransactionOperationsImp.java, sdk/src/main/java/com/meniga/sdk/webservices/MenigaAPI.java, sdk/src/main/java/com/meniga/sdk/webservices/PersistenceDelegate.java, sdk/src/main/java/com/meniga/sdk/webservices/WebClient.java
Added a way to get suggested transactions from the transaction update endpoints.
=> feat/MOBILE-1618 User is prompted about re-categorising all

sdk/build.gradle, sdk/src/main/java/com/meniga/sdk/models/organizations/MenigaRealm.java
Creating a convenience call for transferring user accounts.
=> feat/MOBILE-2786 Re-integrate the account transfer feature

sdk/build.gradle, sdk/src/main/java/com/meniga/sdk/models/transactions/ParsedData.java
Fixing a small error in transaction's parsedData field, the value field did not have the correct name.
=> bug/SDPOSTE-46 Android SDK parsedData not accessible

sdk/build.gradle, sdk/src/main/java/com/meniga/sdk/models/user/MenigaUser.java, sdk/src/main/java/com/meniga/sdk/models/user/MenigaUserMetaData.java, sdk/src/main/java/com/meniga/sdk/models/user/operators/MenigaUserOperations.java, sdk/src/main/java/com/meniga/sdk/models/user/operators/MenigaUserOperationsImp.java, sdk/src/main/java/com/meniga/sdk/webservices/APIConst.java, sdk/src/main/java/com/meniga/sdk/webservices/MenigaAPI.java, sdk/src/main/java/com/meniga/sdk/webservices/PersistenceDelegate.java, sdk/src/main/java/com/meniga/sdk/webservices/requests/GetUserMetaData.java
Added the user metadata endpoint to the sdk.
=> bug/SDPOSTE-45 Android SDK me/metadata access

sdk/build.gradle, sdk/src/main/java/com/meniga/sdk/eventconverters/generic/BaseEventConverter.java, sdk/src/main/java/com/meniga/sdk/eventconverters/generic/BaseMenigaFeedItem.java
Fixing errors in account feed event so that the object store can hand…le it correctly.
=> bug/MOBILE-2799 Feed cache

sdk/build.gradle, sdk/src/main/java/com/meniga/sdk/eventconverters/generic/BaseEventConverter.java, sdk/src/main/java/com/meniga/sdk/eventconverters/generic/BaseMenigaFeedItem.java
Fixing a problem with the BaseFeedItem so that it can be correctly serialized.
=> bug/MOBILE-2854 New Data label always presented in Feed

sdk/src/main/java/com/meniga/sdk/models/merchants/MenigaMerchantLocation.java
Fixing parcelable for merchant location.
=> bug/MOBILE-2839 Parcelable Merchant Location

sdk/src/main/java/com/meniga/sdk/models/transactions/TransactionsFilter.java, sdk/src/main/java/com/meniga/sdk/webservices/MenigaAPI.java
=> improv/SDPOSTE-52 MenigaTransaction fetch optional inlude request

sdk/src/main/java/com/meniga/sdk/converters/MenigaFeedConverter.kt
Fixing a problem that causes the feed not to load.
=> feat/MOBILE-2971 Feed problem

sdk/src/main/java/com/meniga/sdk/converters/MenigaTransactionsConverter.kt, sdk/src/main/java/com/meniga/sdk/models/user/MenigaUser.java, sdk/src/main/java/com/meniga/sdk/models/user/operators/MenigaUserOperations.java, sdk/src/main/java/com/meniga/sdk/models/user/operators/MenigaUserOperationsImp.java, sdk/src/main/java/com/meniga/sdk/webservices/MenigaAPI.java, sdk/src/main/java/com/meniga/sdk/webservices/PersistenceDelegate.java, sdk/src/main/java/com/meniga/sdk/webservices/requests/SaveMetaData.kt
Now able to save user metadata.
=> feat/MOBILE-3020 Save user meta data

sdk/src/main/java/com/meniga/sdk/models/sync/MenigaSync.kt
Fixing a bug that causes first time syncing not to work.
=> bug/MOBILE-3024 Sync fails when run for first time

sdk/src/main/java/com/meniga/sdk/models/upcoming/MenigaUpcomingCronExpression.java, sdk/src/main/java/com/meniga/sdk/models/upcoming/operators/MenigaUpcomingOperationsImp.java, sdk/src/main/java/com/meniga/sdk/webservices/requests/UpdateUpcoming.java
Making some changes to the Upcoming feature, so that it corresponds with the API.
=> feat/MOBILE-3065 Upcoming - Present predictions

sdk/src/main/java/com/meniga/sdk/models/upcoming/MenigaUpcomingCronExpression.java, sdk/src/test/java/com/meniga/sdk/models/upcoming/MenigaUpcomingTest.java
Implementing changes to the Upcoming sdk, day of month is a proper cron expression now.
=> bug/MOBILE-3178 Upcoming pattern cron expression

sdk/src/main/java/com/meniga/sdk/models/upcoming/MenigaUpcomingCronExpression.java, sdk/src/test/java/com/meniga/sdk/models/upcoming/MenigaUpcomingTest.java
Another field needs to be String rather than an enum.
=> Cron expression fix for upcoming

sdk/src/main/java/com/meniga/sdk/models/user/MenigaUser.java, sdk/src/main/java/com/meniga/sdk/models/user/operators/MenigaUserOperations.java, sdk/src/main/java/com/meniga/sdk/models/user/operators/MenigaUserOperationsImp.java, sdk/src/main/java/com/meniga/sdk/webservices/APIConst.java, sdk/src/main/java/com/meniga/sdk/webservices/MenigaAPI.java, sdk/src/main/java/com/meniga/sdk/webservices/PersistenceDelegate.java, sdk/src/main/java/com/meniga/sdk/webservices/requests/ResetPasswordWithToken.kt
It's now possible to reset user passwords using a token in the sdk.
=> improv/MOBILE-3266 Reset password from email link

sdk/src/main/java/com/meniga/sdk/models/accounts/MenigaAccount.kt, sdk/src/main/java/com/meniga/sdk/models/accounts/MenigaAccountOperationsImp.kt, sdk/src/test/java/com/meniga/sdk/models/accounts/MenigaAccountFactory.kt
Adding missing fields to the account class.
=> improv/SDPOSTE-78 Android SDK MenigaAccount is missing fields

sdk/src/main/java/com/meniga/sdk/models/challenges/enums/CustomChallengeColor.java
Should not provide color resources in the SDK.
=> bug/MOBILE-3479 No colors in SDK

sdk/build.gradle, sdk/src/main/java/com/meniga/sdk/webservices/APIRequest.java, sdk/src/main/java/com/meniga/sdk/webservices/MenigaAPI.java, sdk/src/main/java/com/meniga/sdk/webservices/PersistenceDelegate.java
Changing the generic api request to make it more flexible.
=> feat/MOBILE-3474 integrate Intercom

sdk/src/main/java/com/meniga/sdk/models/serverpublic/MenigaPublicSettings.java, sdk/src/main/java/com/meniga/sdk/models/transactions/MenigaTransaction.java, sdk/src/main/java/com/meniga/sdk/models/user/MenigaUserProfile.java, sdk/src/test/java/com/meniga/sdk/models/serverpublic/MenigaPublicSettingsTest.java, sdk/src/test/resources/raw/transaction.json
Adding the bookedAmount field to the transaction data object.
=> improv/MOBILE-2657 Change from systemCurrency to userCurrency

sdk/src/main/java/com/meniga/sdk/models/userevents/enums/UserEventType.java
Adding missing user event types.
=> improv/MOBILE-3581 Settings: Notifications - Upcoming translation partially missing

sdk/src/main/java/com/meniga/sdk/models/transactions/SeriesSelector.java, sdk/src/main/java/com/meniga/sdk/models/transactions/TransactionsFilter.java, sdk/src/main/java/com/meniga/sdk/models/transactions/enums/TransactionSortField.java, sdk/src/main/java/com/meniga/sdk/models/transactions/operators/MenigaTransactionSeriesOperationsImp.java, sdk/src/test/java/com/meniga/sdk/models/transactions/TransactionsFilterTest.java
Added sort order to transactions filter.
=> feat/MOBILE-3616 Add "sort" to the transactions filter for sorting api transaction results

sdk/src/main/java/com/meniga/sdk/models/transactions/TransactionsFilter.java, sdk/src/test/java/com/meniga/sdk/models/transactions/TransactionsFilterTest.java
Added onlyUncleared to the transaction filter.
=> improv/MOBILE-3716 Update sdk to get only isUncleared in GetTransactions (new boolean)

.github/workflows/tests.yml, .travis.yml, README.md
Migrato tests to github actions
=> Migrato tests to github actions
